apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: sample-python-app
spec:
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: PORT
      value: "8080"
    path: ../..
  ports:
  - name: main
    port: 8080
